name: CI
on:
  pull_request:
  push:

jobs:
  hyllama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
